test-management-system/api/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path("create_project/", CreateProject.as_view(), name="create_project"),
    path("create_version/", CreateVersion.as_view(), name="create_version"),
    path("pull_version/", UpdateVersion.as_view(), name="pull_version"),
    path("projects/<id>/", GetProject.as_view(), name="get_project"),
    path("project_versions/<id>/", GetVersion.as_view(), name="get_version"),
    path(
        "project_versions_with_coverage/<version_id>/",
        GetVersionWithCoverage.as_view(),
        name="get_version_with_coverage",
    ),
    path(
        "projects_with_last_version/<project_id>/",
        GetProjectWithLastVersion.as_view(),
        name="projects_with_last_version",
    ),
    path("update_test/", UpdateProjectTest.as_view(), name="update_test"),
    path("delete_version/<id>/", DeleteVersion.as_view(), name="delete_version"),
    path("create_file/", CreateFile.as_view(), name="create_file"),
    path("push_files/", PushFiles.as_view(), name="push_files"),
    path("get_file_text/<file_id>/", GetFileText.as_view(), name="get_file_text"),
    path("update_file/<file_id>/", UpdateFile.as_view(), name="update_file"),
    path("get_test_text/<test_id>/", GetTestText.as_view(), name="get_test_text"),
    path("get_file_auto_tests/<file_id>/", GetFileAutoSteps.as_view(), name="get_file_auto_tests"),
    path("get_common_auto_tests/<version_id>/", GetCommonAutoSteps.as_view(), name="get_common_auto_tests"),
    path("get_updated_files/<version_id>/", GetUpdatedFiles.as_view(), name="get_updated_files")
]

test-management-system/frontend/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from .views import *
from django.templatetags.static import static


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("login/", LoginForm.as_view(), name="login"),
    path("register/", RegisterForm.as_view(), name="register"),
    path("projects/<int:project_id>/", ProjectReactBase.as_view(), name="project_page"),
]

urlpatterns += [
    path("favicon.ico", RedirectView.as_view(url=static("favicon.ico"), permanent=True))
]

test-management-system/test_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(("api.urls", "api1"), namespace="api1")),
    path("", include(("frontend.urls", "api"), namespace="frontend")),
    path("user_api/", include(("users.urls", "user_api"), namespace="user_api")),
]

test-management-system/users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        "generate_register_token/",
        views.RegisterTokenGenerator.as_view(),
        name="generate_register_token",
    ),
    path("register/", views.UserRegister.as_view(), name="register"),
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.UserLogout.as_view(), name="logout"),
    path("me/", views.UserView.as_view(), name="user"),
]

test-management-system/frontend/models.py
from django.db import models

# Create your models here.

test-management-system/frontend/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework.permissions import IsAuthenticated, AllowAny
from users.permissions import RegistrationTokenPermission
from rest_framework.views import APIView
from api import models
from rest_framework.exceptions import NotAuthenticated
from django.shortcuts import redirect
from django.urls import reverse


class IndexView(APIView):
    def get(self, request, format=None):
        projects = models.Project.objects.all()
        contex = {"projects": projects}
        return render(request, "index.html", contex)


class LoginForm(APIView):
    permission_classes = [
        AllowAny,
    ]

    def get(self, request, format=None):
        return render(request, "login_form.html")


class RegisterForm(APIView):
    permission_classes = [
        RegistrationTokenPermission,
    ]

    def get(self, request, format=None):
        return render(request, "register_form.html")


class ProjectReactBase(APIView):
    def get(self, request, project_id):
        project = get_object_or_404(models.Project, id=project_id)
        return render(request, "react/project_page.html")


class AccessTokens(APIView):
    def get(self, request):
        tokens = models.GitAccessToken.objects.all()

test-management-system/frontend/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
        <link rel="stylesheet" href="{% static 'css/projects_list.css' %}" />
  
        
        <title>Test Management System</title>
    </head>
    <body>
        {% include "navbar.html"%}

        {% include "projects_list.html"%}
        
    
    </body>
</html>

test-management-system/frontend/templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'css/forms.css' %}" />
        <title>Test Management System</title>
    </head>
    <body>
        <div class="d-flex justify-content-center align-items-center mt-5">
            <div class="card">
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item text-center">
                        <a class="nav-link active btl" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Log In into Account</a>
                    </li>
                </ul>

                <div class="tab-content" id="pills-tabContent">
                    <h5 class="text-center text-danger" id="formError"></h5>   
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                        <div class="form px-4 pt-3">
                            <input type="text" name="" class="form-control form-field" placeholder="E-Mail" id="emailField"/>
                            <input type="password" name="" class="form-control form-field" placeholder="Password" id="passwordField" />
                            <button class="btn btn-dark btn-block" id="LoginButton" href="{% url 'user_api:login' %}">Log In</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'js/login_form.js' %}"></script>
    </body>
</html>

test-management-system/frontend/templates/navbar.html
{% load static %}

<nav class="navbar navbar-dark bg-primary">
    <a calss="navbar-title-link" href="{% url 'frontend:index' %}"><p class="navbar-title">Test Managment System</p></a>

    <div class="navbar-user-actions">
        <h4 class="nav-link">{{ user.get_username }} </h4>
        <button href="{% url 'user_api:logout' %}" class="btn btn-danger navbar-button" role="button" id="LogoutButton" onclick="PerformLogout()">Log Out</button>
        {% if user.is_superuser %}
        <button type="button" class="btn btn-success navbar-button" data-bs-toggle="modal" data-bs-target="#createRegisterLink">Create Sign-Up Link</button>
        {% endif %}
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="createRegisterLink" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Create registration link</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="input-group mb-3">
        <button class="btn btn-outline-secondary generate-register-link" type="button" id="generate-link" href="{% url 'user_api:generate_register_token' %}">Create</button>
        <textarea disabled type="text" class="form-control generated-url-text" placeholder="" id="register-link" aria-describedby="button-addon1" rows="4"></textarea>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="copy-registration-link">Copy</button>
      </div>
    </div>
  </div>
</div>

<script src="{% static 'js/navbar.js' %}"></script>

test-management-system/frontend/templates/projects_list.html
{% load static %}
<div class="projects-list">
  <div class="list-group">

      <button type="button" class="list-group-item list-group-item-action disabled"> <h3>Projects List</h3> </button>
      {% for project in projects %}
        <div class="project-link-container">
          <a class="project-link" href="{% url 'frontend:project_page'  project_id=project.id%}"><button type="button" class="list-group-item list-group-item-action">{{ project.name }}</button></a>
        </div>
      {% endfor %}
      {% if user.is_superuser %}
        <button type="button" class="btn btn-outline-success add-project-button" data-bs-toggle="modal" data-bs-target="#createProject">+ Create Project</button>
      {% endif %}
  </div>
</div>

<div class="modal fade" id="createProject" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Create Project </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Project's name" aria-label="Username" aria-describedby="addon-wrapping" id="newProjectName">
        </div>

        <div class="error-container">
         <p class="text-danger field-error-message" id="nameFieldErrorMessage"></p>
        </div> 

        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Repository link" aria-label="RepoLink" aria-describedby="addon-wrapping" id="newProjectRepoLink">
        </div>
        <div class="error-container">
         <p class="text-danger field-error-message" id="repoLinkFieldErrorMessage"></p>
        </div>

        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Git access token" aria-label="GitAccessToken" aria-describedby="addon-wrapping" id="newProjectGitAccessToken">
        </div>
        <div class="error-container">
         <p class="text-danger field-error-message" id="GitTokenFieldErrorMessage"></p>
        </div>

        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Git username (you can leave it blank if you use Project access token" aria-label="GitUsername" aria-describedby="addon-wrapping" id="newProjectGitUsername">
        </div>
        <div class="error-container">
         <p class="text-danger field-error-message" id="GitUsernameFieldErrorMessage"></p>
        </div>

        <div class="input-group mb-3 input-block">
          <div class="grow-max">
            <div class="input-group mb-3 input-with-tooltip">
              <input type="text" class="form-control" placeholder=".feature files folder (leave blank to pull all test files)" aria-label="filesFolder" aria-describedby="addon-wrapping" id="newProjectFilesFolder">
            </div>

            <div class="error-container">
             <p class="text-danger field-error-message" id="filesFolderFieldErrorMessage"></p>
            </div>
          </div>

          <div class="grow-min">
            <div class="input-group mb-3 input-with-tooltip">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="newProjectSmartMode">
                <label class="form-check-label" for="newProjectSmartMode">
                  Smart mode
                </label>
              </div>
                <img src="{%  static 'icons/tool-tip.png' %}" type="button"  rel="tooltip" data-toggle="tooltip" data-placement="top" title="Smart mode will analyze what .feature files are covered with auto-testing">
            </div>

            <div class="error-container">
             <p class="text-danger field-error-message" id="smartModeFieldErrorMessage"></p>
            </div>
          </div>
        </div>


        <div class="input-group mb-3 input-with-tooltip">
          <input type="text"
                 class="form-control"
                 placeholder="Common auto-test folder inside .feature files comma-separated folders"
                 aria-label="filesFolder"
                 aria-describedby="addon-wrapping"
                 id="newProjectCommonAutoTestsFolder">
        </div>
        <div class="error-container">
         <p class="text-danger field-error-message" id="commonAutoTestsFolderFieldErrorMessage"></p>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="createProjectButton" href="{% url 'api1:create_project' %}">Create</button>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/projects_list.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $("[rel='tooltip']").tooltip();
    });
</script>

test-management-system/frontend/templates/register_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'css/forms.css' %}" />

        <title>Test Managment System</title>
    </head>
    <body>
        <div class="d-flex justify-content-center align-items-center mt-5">
            <div class="card">
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item text-center">
                        <a class="nav-link active btl" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Register</a>
                    </li>
                </ul>

                <div class="tab-content" id="pills-tabContent">
                    <h5 class="text-center text-danger" id="formError"></h5>   
                    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                        <div class="form px-4 pt-3">
                            <input type="text" name="" class="form-control form-field" placeholder="E-Mail" id="emailField"/>
                            <p class="text-danger field-error-message" id="emailFieldErrorMessage"></p>

                            <input type="text" name="" class="form-control form-field" placeholder="Name" id="nameField" />
                            <p class="text-danger field-error-message" id="nameFieldErrorMessage"></p>

                            <input type="password" name="" class="form-control form-field" placeholder="Password" id="passwordField" />
                            <p class="text-danger field-error-message" id="passwordFieldErrorMessage"></p>

                            <input type="password" name="" class="form-control form-field" placeholder="Confirm Password" id="passwordConfirmField" />
                            <p class="text-danger field-error-message" id="passwordConfirmFieldErrorMessage"></p>

                            <button class="btn btn-dark btn-block" id="RegisterButton" href="{% url 'user_api:register' %}">Sign Up</button>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'js/register_form.js' %}"></script>
    </body>
</html>